import * as React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { FileText, CheckCircle2, TrendingUp, AlertTriangle, ArrowLeft, Download } from 'lucide-react';

export function ReportsTab({ assignment, reports, onReload }: { assignment: any; reports: any[]; onReload: () => void }) {
  const [viewingReport, setViewingReport] = React.useState<any>(null);

  if (viewingReport) {
    const r = viewingReport;
    return (
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <div>
            <Button variant="ghost" size="sm" onClick={() => setViewingReport(null)} className="-ml-2 mb-2">
              <ArrowLeft className="h-4 w-4 mr-1" /> Back to Reports
            </Button>
            <CardTitle>Report for {new Date(r.report_date).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</CardTitle>
            <CardDescription>Generated by {r.lead_inspector || 'Verifier'}</CardDescription>
          </div>
          <Badge variant="outline" className="bg-primary/5 text-primary border-primary/20">
            {r.status === 'submitted' ? 'Finalized' : 'Draft'}
          </Badge>
        </CardHeader>
        <CardContent className="space-y-6 pt-4">
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
            <div className="rounded-lg bg-muted/50 p-3 text-center">
              <p className="text-xl font-bold font-display text-primary">{r.overall_health_score}/100</p>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Health Score</p>
            </div>
            <div className="rounded-lg bg-muted/50 p-3 text-center">
              <p className="text-xl font-bold font-display">{r.tree_survival_rate || 0}%</p>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Survival Rate</p>
            </div>
            <div className="rounded-lg bg-muted/50 p-3 text-center">
              <p className="text-xl font-bold font-display">{r.carbon_estimate_tons?.toFixed(1) || '0'} t</p>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Carbon Est.</p>
            </div>
            <div className="rounded-lg bg-muted/50 p-3 text-center">
              <p className="text-xl font-bold font-display flex items-center justify-center gap-1">
                {r.delta_tree_count > 0 ? 'Positive' : 'Stable'} <TrendingUp className="h-4 w-4 text-emerald-500" />
              </p>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Growth Trend</p>
            </div>
            <div className="rounded-lg bg-muted/50 p-3 text-center">
              <p className="text-xl font-bold font-display flex items-center justify-center gap-1">
                {r.risk_level || 'Low'} <AlertTriangle className="h-4 w-4 text-amber-500" />
              </p>
              <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Risk Level</p>
            </div>
          </div>

          <div className="space-y-4 text-sm">
            <div className="grid md:grid-cols-2 gap-4">
              <div>
                <h4 className="font-medium text-muted-foreground mb-1">Forest Assessment</h4>
                <div className="bg-muted/30 p-3 rounded-lg space-y-2">
                  <p><span className="font-medium">Total Trees:</span> {r.current_tree_count || 'N/A'}</p>
                  <p><span className="font-medium">Canopy Coverage:</span> {r.canopy_coverage || 'N/A'}%</p>
                  <p><span className="font-medium">Tree Health:</span> {r.tree_health || 'N/A'}</p>
                  <p><span className="font-medium">Dominant Species:</span> {r.dominant_species || 'N/A'}</p>
                </div>
              </div>
              <div>
                <h4 className="font-medium text-muted-foreground mb-1">Carbon & Biodiversity</h4>
                <div className="bg-muted/30 p-3 rounded-lg space-y-2">
                  <p><span className="font-medium">Soil Carbon:</span> {r.soil_carbon || 0} t</p>
                  <p><span className="font-medium">Species Observed:</span> {r.species_observed || 'N/A'}</p>
                  <p><span className="font-medium">Habitat Quality:</span> {r.habitat_quality || 'N/A'}</p>
                  <p><span className="font-medium">Methodology:</span> {r.methodology || 'N/A'}</p>
                </div>
              </div>
            </div>
            <div>
              <h4 className="font-medium text-muted-foreground mb-1">Final Summary & Notes</h4>
              <div className="bg-muted/30 p-3 rounded-lg space-y-2">
                <p><span className="font-medium text-primary">Recommendation:</span> {r.recommendation || 'None'}</p>
                <p><span className="font-medium text-muted-foreground">Internal Notes:</span> {r.auditor_notes || 'None provided.'}</p>
                <p><span className="font-medium text-muted-foreground">Partner Notes:</span> {r.partner_notes || 'None provided.'}</p>
              </div>
            </div>
          </div>
          
          <div className="pt-4 flex justify-end">
             <Button variant="default"><Download className="h-4 w-4 mr-2" /> Download Official PDF Report</Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold">Generated Reports</h2>
          <p className="text-sm text-muted-foreground">Access historical monitoring reports and generated PDFs.</p>
        </div>
      </div>

      {reports.length === 0 ? (
        <Card className="border-dashed">
          <CardContent className="flex flex-col items-center justify-center py-12 text-center">
            <FileText className="h-10 w-10 text-muted-foreground mb-4 opacity-50" />
            <h3 className="font-semibold text-foreground mb-1">No reports generated</h3>
            <p className="text-sm text-muted-foreground">Complete a Monthly Monitoring wizard to generate a report.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {reports.map((report) => (
            <Card key={report.id} className="hover:border-primary/50 transition-colors">
              <CardContent className="p-4 flex flex-col md:flex-row md:items-center gap-4 justify-between">
                <div className="flex items-center gap-4">
                  <div className="h-10 w-10 bg-primary/10 text-primary rounded-lg flex items-center justify-center font-semibold">
                    {new Date(report.report_date).toLocaleDateString(undefined, { month: 'short' })}
                  </div>
                  <div>
                    <div className="font-medium">{new Date(report.report_date).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })} Report</div>
                    <div className="text-xs text-muted-foreground mt-0.5 flex items-center gap-2">
                      <span>Health Score: {report.overall_health_score}/100</span>
                      <span>•</span>
                      <span>Trees: {report.current_tree_count || 0}</span>
                      {report.status === 'submitted' && (
                        <>
                          <span>•</span>
                          <span className="text-emerald-600 flex items-center"><CheckCircle2 className="h-3 w-3 mr-1" /> Finalized</span>
                        </>
                      )}
                    </div>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={() => setViewingReport(report)}>
                    View Details
                  </Button>
                  <Button variant="default" size="sm">
                    <Download className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
