import type {
  VerificationApplication,
  AuditReport,
  OfficialRecord,
  VOCAnalytics,
  VOCCalendarEvent,
  VerificationAgency,
} from './voc-types';

export const MOCK_VERIFICATION_AGENCIES: VerificationAgency[] = [
  {
    id: 'ngo-001',
    profile_id: 'verifier-001',
    profile_id_internal: 'vint-001',
    verifier_ids: ['vr-001', 'vr-002'],
    audit_team_ids: ['at-001'],
    regional_office_ids: ['ro-001', 'ro-002'],
    name: 'GreenRoots Foundation',
    logo_url: null,
    registration_number: 'IND/GOV/2018/BCR-4412',
    description: 'GreenRoots Foundation is a leading government-certified verification agency specializing in blue carbon ecosystem restoration. With over 8 years of field experience across South Asia, we have certified 142+ mangrove and wetland restoration projects.',
    mission: 'To accelerate climate action through rigorous, transparent, and science-based verification of blue carbon ecosystems.',
    founded_year: 2018,
    headquarters: 'Mumbai, Maharashtra, India',
    operating_regions: ['Maharashtra', 'Gujarat', 'Odisha', 'Karnataka', 'Tamil Nadu'],
    countries_served: ['India', 'Sri Lanka', 'Bangladesh', 'Maldives'],
    states_covered: ['Maharashtra', 'Gujarat', 'Odisha', 'Karnataka', 'Tamil Nadu', 'Goa', 'Kerala'],
    expertise: ['Mangrove Restoration', 'Blue Carbon', 'Wetlands', 'Coastal Restoration'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Blue Carbon Projects', 'GIS Mapping'],
    supported_ecosystems: ['Mangroves', 'Wetlands', 'Blue Carbon', 'Coastal Restoration'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'ISO 14001' },
      { name: 'Environmental Impact Certified' },
    ],
    projects_certified: 142,
    active_applications: 11,
    avg_verification_days: 18,
    years_of_operation: 8,
    available_audit_teams: 3,
    estimated_review_days: 14,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Sundarbans Mangrove Phase III', status: 'approved', date: '2026-07-01' },
      { project_name: 'Thane Creek Restoration', status: 'approved', date: '2026-06-15' },
      { project_name: 'Pulicat Lake Wetlands', status: 'approved', date: '2026-04-20' },
    ],
  },
  {
    id: 'ngo-002',
    profile_id: 'verifier-002',
    profile_id_internal: 'vint-002',
    verifier_ids: ['vr-003', 'vr-004', 'vr-005'],
    audit_team_ids: ['at-002', 'at-003'],
    regional_office_ids: ['ro-003'],
    name: 'Coastal Verification Services',
    logo_url: null,
    registration_number: 'IND/GOV/2019/BCV-7831',
    description: 'Coastal Verification Services is a nationally accredited verification body with deep expertise in coastal ecosystem certification. Our team of 20+ certified auditors covers the entire Indian coastline.',
    mission: 'Providing credible, science-driven verification that empowers coastal communities and protects marine ecosystems.',
    founded_year: 2019,
    headquarters: 'Chennai, Tamil Nadu, India',
    operating_regions: ['Tamil Nadu', 'Andhra Pradesh', 'Odisha', 'West Bengal', 'Kerala'],
    countries_served: ['India', 'Myanmar', 'Thailand'],
    states_covered: ['Tamil Nadu', 'Andhra Pradesh', 'Odisha', 'West Bengal', 'Kerala', 'Puducherry'],
    expertise: ['Coastal Restoration', 'Mangrove Restoration', 'Biodiversity', 'Wetlands'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Biodiversity Assessment', 'Drone Survey'],
    supported_ecosystems: ['Mangroves', 'Wetlands', 'Coral Reefs', 'Seagrass Beds'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'ISO 14001' },
    ],
    projects_certified: 98,
    active_applications: 7,
    avg_verification_days: 22,
    years_of_operation: 7,
    available_audit_teams: 4,
    estimated_review_days: 16,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Pichavaram Mangrove Expansion', status: 'approved', date: '2026-06-28' },
      { project_name: 'Chilika Lake Conservation', status: 'approved', date: '2026-05-12' },
      { project_name: 'Vembanad Wetlands Project', status: 'approved', date: '2026-03-18' },
    ],
  },
  {
    id: 'ngo-003',
    profile_id: 'verifier-003',
    profile_id_internal: 'vint-003',
    verifier_ids: ['vr-006'],
    audit_team_ids: ['at-004'],
    regional_office_ids: ['ro-004', 'ro-005'],
    name: 'Pacific Mangrove Foundation',
    logo_url: null,
    registration_number: 'IDN/GOV/2020/PMF-2290',
    description: 'Pacific Mangrove Foundation operates across Southeast Asia, providing specialized verification services for mangrove and coastal restoration projects. We have pioneered drone-assisted verification methodologies.',
    mission: 'Leveraging technology and local partnerships to deliver fast, accurate, and scalable verification of nature-based solutions.',
    founded_year: 2020,
    headquarters: 'Jakarta, Indonesia',
    operating_regions: ['Java', 'Sumatra', 'Kalimantan', 'Sulawesi'],
    countries_served: ['Indonesia', 'Philippines', 'Vietnam', 'Malaysia'],
    states_covered: ['DKI Jakarta', 'West Java', 'Central Java', 'East Kalimantan', 'North Sumatra'],
    expertise: ['Mangrove Restoration', 'Blue Carbon', 'Drone Survey', 'Carbon Certification'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Drone Survey', 'Satellite Monitoring'],
    supported_ecosystems: ['Mangroves', 'Seagrass', 'Blue Carbon', 'Peatlands'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'ISO 14001' },
      { name: 'REDD+ Certified' },
    ],
    projects_certified: 67,
    active_applications: 9,
    avg_verification_days: 15,
    years_of_operation: 6,
    available_audit_teams: 2,
    estimated_review_days: 12,
    availability: 'limited',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Mahakam Delta Restoration', status: 'approved', date: '2026-07-05' },
      { project_name: 'Batangas Mangrove Park', status: 'approved', date: '2026-05-22' },
      { project_name: 'Ca Mau Mangrove Reserve', status: 'approved', date: '2026-04-10' },
    ],
  },
  {
    id: 'ngo-004',
    profile_id: 'verifier-004',
    profile_id_internal: 'vint-004',
    verifier_ids: ['vr-007', 'vr-008'],
    audit_team_ids: ['at-005'],
    regional_office_ids: ['ro-006'],
    name: 'Global Blue Carbon Network',
    logo_url: null,
    registration_number: 'KEN/GOV/2021/GBN-5567',
    description: 'Global Blue Carbon Network is an internationally recognized verification body focused on African and Indian Ocean coastal ecosystems. We partner with local communities to ensure equitable and thorough verification.',
    mission: 'Building trust in blue carbon markets through community-centered verification and transparent reporting.',
    founded_year: 2021,
    headquarters: 'Nairobi, Kenya',
    operating_regions: ['Coast Province', 'Nyanza', 'Western Kenya'],
    countries_served: ['Kenya', 'Tanzania', 'Mozambique', 'Madagascar', 'Seychelles'],
    states_covered: ['Mombasa', 'Kilifi', 'Lamu', 'Kwale', 'Tana River'],
    expertise: ['Blue Carbon', 'Wetlands', 'Forest Restoration', 'Biodiversity', 'Community Engagement'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Biodiversity Assessment', 'Community Impact Assessment'],
    supported_ecosystems: ['Mangroves', 'Wetlands', 'Blue Carbon', 'Coastal Forests'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'Gold Standard' },
    ],
    projects_certified: 43,
    active_applications: 4,
    avg_verification_days: 25,
    years_of_operation: 5,
    available_audit_teams: 2,
    estimated_review_days: 18,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Mikoko Pamoja Extension', status: 'approved', date: '2026-06-10' },
      { project_name: 'Gazi Bay Blue Carbon', status: 'approved', date: '2026-04-25' },
      { project_name: 'Rufiji Delta Restoration', status: 'approved', date: '2026-02-18' },
    ],
  },
  {
    id: 'ngo-005',
    profile_id: 'verifier-005',
    profile_id_internal: 'vint-005',
    verifier_ids: ['vr-009', 'vr-010', 'vr-011'],
    audit_team_ids: ['at-006', 'at-007'],
    regional_office_ids: ['ro-007', 'ro-008'],
    name: 'Wetlands Verification Corp',
    logo_url: null,
    registration_number: 'BRA/GOV/2020/WVC-8834',
    description: 'Wetlands Verification Corp is South America\'s premier verification body for wetland and mangrove ecosystems. Our team of 30+ specialists covers the entire Amazon basin and Atlantic Forest corridor.',
    mission: 'Ensuring the highest standards of verification for wetland carbon projects across Latin America.',
    founded_year: 2020,
    headquarters: 'São Paulo, Brazil',
    operating_regions: ['São Paulo', 'Bahia', 'Maranhão', 'Pará', 'Amapá'],
    countries_served: ['Brazil', 'Colombia', 'Ecuador', 'Argentina'],
    states_covered: ['São Paulo', 'Bahia', 'Maranhão', 'Pará', 'Amapá', 'Ceará', 'Pernambuco'],
    expertise: ['Wetlands', 'Mangrove Restoration', 'Forest Restoration', 'Blue Carbon', 'River Delta Systems'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Satellite Monitoring', 'Biodiversity Assessment'],
    supported_ecosystems: ['Wetlands', 'Mangroves', 'River Deltas', 'Floodplain Forests'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'ISO 14001' },
      { name: 'Verra VCS Certified' },
    ],
    projects_certified: 85,
    active_applications: 14,
    avg_verification_days: 20,
    years_of_operation: 6,
    available_audit_teams: 5,
    estimated_review_days: 15,
    availability: 'limited',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Amazon Delta Mangroves', status: 'approved', date: '2026-07-08' },
      { project_name: 'Cananéia Estuary Project', status: 'approved', date: '2026-05-30' },
      { project_name: 'Guajirá Coastal Wetlands', status: 'approved', date: '2026-03-22' },
    ],
  },
  {
    id: 'ngo-006',
    profile_id: 'verifier-006',
    profile_id_internal: 'vint-006',
    verifier_ids: ['vr-012'],
    audit_team_ids: ['at-008'],
    regional_office_ids: ['ro-009'],
    name: 'Nordic Carbon Verification',
    logo_url: null,
    registration_number: 'NOR/GOV/2022/NCV-1123',
    description: 'Nordic Carbon Verification brings Scandinavian precision to global carbon certification. Specializing in cold-water coastal ecosystems and seagrass meadows.',
    mission: 'Applying Nordic standards of excellence to ensure credible carbon verification worldwide.',
    founded_year: 2022,
    headquarters: 'Oslo, Norway',
    operating_regions: ['Nordic Region', 'Northern Europe', 'Arctic Coastlines'],
    countries_served: ['Norway', 'Sweden', 'Finland', 'Iceland', 'Denmark'],
    states_covered: ['Oslo', 'Bergen', 'Tromsø', 'Gothenburg', 'Helsinki'],
    expertise: ['Seagrass', 'Blue Carbon', 'Cold-Water Ecosystems', 'Arctic Coastal'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Seagrass Mapping'],
    supported_ecosystems: ['Seagrass Meadows', 'Kelp Forests', 'Arctic Coastal Wetlands'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'ISO 14001' },
      { name: 'EU ETS Certified' },
    ],
    projects_certified: 31,
    active_applications: 5,
    avg_verification_days: 12,
    years_of_operation: 4,
    available_audit_teams: 2,
    estimated_review_days: 10,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Oslofjord Seagrass Recovery', status: 'approved', date: '2026-06-20' },
      { project_name: 'Skagerrak Coastal Restoration', status: 'approved', date: '2026-04-05' },
      { project_name: 'Bothnia Bay Wetlands', status: 'approved', date: '2026-01-15' },
    ],
  },
  {
    id: 'ngo-007',
    profile_id: 'verifier-007',
    profile_id_internal: 'vint-007',
    verifier_ids: ['vr-013', 'vr-014'],
    audit_team_ids: ['at-009', 'at-010'],
    regional_office_ids: ['ro-010', 'ro-011'],
    name: 'Asia Pacific Carbon Council',
    logo_url: null,
    registration_number: 'SGP/GOV/2019/APCC-6678',
    description: 'Asia Pacific Carbon Council is the region\'s most comprehensive verification body, covering 12 countries and offering end-to-end certification services for nature-based solutions.',
    mission: 'Unifying verification standards across the Asia-Pacific to build trust in carbon markets.',
    founded_year: 2019,
    headquarters: 'Singapore',
    operating_regions: ['Southeast Asia', 'South Asia', 'East Asia', 'Pacific Islands'],
    countries_served: ['Singapore', 'India', 'Indonesia', 'Philippines', 'Thailand', 'Vietnam', 'Australia', 'Fiji'],
    states_covered: ['Singapore', 'Maharashtra', 'Java', 'Luzon', 'Queensland'],
    expertise: ['Mangrove Restoration', 'Blue Carbon', 'Wetlands', 'Seagrass', 'Forest Restoration', 'Biodiversity'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Satellite Monitoring', 'Drone Survey', 'Community Impact Assessment'],
    supported_ecosystems: ['Mangroves', 'Wetlands', 'Seagrass', 'Coastal Forests', 'Coral Reefs'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'ISO 14001' },
      { name: 'Gold Standard' },
      { name: 'Verra VCS Certified' },
    ],
    projects_certified: 176,
    active_applications: 18,
    avg_verification_days: 16,
    years_of_operation: 7,
    available_audit_teams: 6,
    estimated_review_days: 13,
    availability: 'limited',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Sundarbans Cross-Border Initiative', status: 'approved', date: '2026-07-12' },
      { project_name: 'Tonle Sap Wetland Restoration', status: 'approved', date: '2026-06-01' },
      { project_name: 'Great Barrier Reef Seagrass', status: 'approved', date: '2026-04-28' },
    ],
  },
  {
    id: 'ngo-008',
    profile_id: 'verifier-008',
    profile_id_internal: 'vint-008',
    verifier_ids: ['vr-015'],
    audit_team_ids: ['at-011'],
    regional_office_ids: ['ro-012'],
    name: 'West Africa Blue Carbon Initiative',
    logo_url: null,
    registration_number: 'NGA/GOV/2023/WABC-3345',
    description: 'West Africa Blue Carbon Initiative focuses on verifying mangrove and wetland restoration projects across the West African coastline, with a strong emphasis on community-led conservation.',
    mission: 'Empowering West African coastal communities through accessible and transparent carbon verification.',
    founded_year: 2023,
    headquarters: 'Lagos, Nigeria',
    operating_regions: ['Lagos', 'Niger Delta', 'Cross River', 'Akwa Ibom'],
    countries_served: ['Nigeria', 'Ghana', 'Senegal', 'Cameroon', 'Gambia'],
    states_covered: ['Lagos', 'Rivers', 'Cross River', 'Akwa Ibom', 'Delta'],
    expertise: ['Mangrove Restoration', 'Community Engagement', 'Wetlands', 'Blue Carbon'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Community Impact Assessment'],
    supported_ecosystems: ['Mangroves', 'Wetlands', 'Coastal Lagoons'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
    ],
    projects_certified: 19,
    active_applications: 3,
    avg_verification_days: 28,
    years_of_operation: 3,
    available_audit_teams: 1,
    estimated_review_days: 21,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Niger Delta Mangrove Phase I', status: 'approved', date: '2026-05-18' },
      { project_name: 'Keta Lagoon Restoration', status: 'approved', date: '2026-03-05' },
      { project_name: 'Senegal River Delta', status: 'approved', date: '2026-01-22' },
    ],
  },
  {
    id: 'ngo-009',
    profile_id: 'verifier-009',
    profile_id_internal: 'vint-009',
    verifier_ids: ['vr-016', 'vr-017'],
    audit_team_ids: ['at-012', 'at-013'],
    regional_office_ids: ['ro-013', 'ro-014'],
    name: 'Mediterranean Blue Carbon Alliance',
    logo_url: null,
    registration_number: 'ESP/GOV/2021/MBCA-9012',
    description: 'Mediterranean Blue Carbon Alliance operates across the Mediterranean basin, providing specialized verification for seagrass meadows, coastal lagoons, and salt marsh restoration projects. Our multi-national team covers 9 Mediterranean countries.',
    mission: 'Protecting Mediterranean blue carbon ecosystems through rigorous, cross-border verification and scientific collaboration.',
    founded_year: 2021,
    headquarters: 'Barcelona, Spain',
    operating_regions: ['Catalonia', 'Andalusia', 'Provence', 'Sicily', 'Attica'],
    countries_served: ['Spain', 'France', 'Italy', 'Greece', 'Croatia', 'Tunisia', 'Morocco', 'Turkey', 'Montenegro'],
    states_covered: ['Catalonia', 'Andalusia', 'Provence-Alpes-Côte d\'Azur', 'Sicily', 'Attica', 'Dubrovnik-Neretva'],
    expertise: ['Seagrass', 'Salt Marsh', 'Coastal Restoration', 'Blue Carbon', 'Marine Biodiversity'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Seagrass Mapping', 'Underwater Survey'],
    supported_ecosystems: ['Seagrass Meadows', 'Salt Marshes', 'Coastal Lagoons', 'Maquis Shrubland'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'ISO 14001' },
      { name: 'EU LIFE Programme Certified' },
    ],
    projects_certified: 54,
    active_applications: 6,
    avg_verification_days: 19,
    years_of_operation: 5,
    available_audit_teams: 3,
    estimated_review_days: 14,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Posidonia Oceanica Recovery — Balearics', status: 'approved', date: '2026-07-02' },
      { project_name: 'Venetian Lagoon Salt Marsh Restoration', status: 'approved', date: '2026-05-15' },
      { project_name: 'Gulf of Tunis Seagrass Revival', status: 'approved', date: '2026-03-28' },
    ],
  },
  {
    id: 'ngo-010',
    profile_id: 'verifier-010',
    profile_id_internal: 'vint-010',
    verifier_ids: ['vr-018', 'vr-019'],
    audit_team_ids: ['at-014'],
    regional_office_ids: ['ro-015'],
    name: 'Oceania Carbon Standards',
    logo_url: null,
    registration_number: 'AUS/GOV/2020/OCS-4456',
    description: 'Oceania Carbon Standards is Australia and Pacific Islands\' leading independent verification body for blue carbon and coastal ecosystem projects. We specialize in large-scale mangrove and tidal wetland certification.',
    mission: 'Setting the gold standard for carbon verification across Oceania through scientific rigour and community partnership.',
    founded_year: 2020,
    headquarters: 'Sydney, Australia',
    operating_regions: ['New South Wales', 'Queensland', 'Western Australia', 'Pacific Islands'],
    countries_served: ['Australia', 'Papua New Guinea', 'Fiji', 'Solomon Islands', 'Vanuatu'],
    states_covered: ['New South Wales', 'Queensland', 'Western Australia', 'Northern Territory'],
    expertise: ['Mangrove Restoration', 'Tidal Wetlands', 'Blue Carbon', 'Coral Reef Monitoring', 'Seagrass'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Satellite Monitoring', 'Drone Survey', 'Aerial Assessment'],
    supported_ecosystems: ['Mangroves', 'Tidal Wetlands', 'Seagrass', 'Coral Reefs', 'Coastal Dunes'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'ISO 14001' },
      { name: 'Gold Standard' },
      { name: 'CDM Certified' },
    ],
    projects_certified: 72,
    active_applications: 8,
    avg_verification_days: 14,
    years_of_operation: 6,
    available_audit_teams: 4,
    estimated_review_days: 11,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Moreton Bay Mangrove Expansion', status: 'approved', date: '2026-07-10' },
      { project_name: 'Torres Strait Tidal Restoration', status: 'approved', date: '2026-05-25' },
      { project_name: 'Suva Harbor Seagrass Initiative', status: 'approved', date: '2026-04-08' },
    ],
  },
  {
    id: 'ngo-011',
    profile_id: 'verifier-011',
    profile_id_internal: 'vint-011',
    verifier_ids: ['vr-020', 'vr-021', 'vr-022'],
    audit_team_ids: ['at-015', 'at-016'],
    regional_office_ids: ['ro-016', 'ro-017'],
    name: 'Caribbean Basin Blue Carbon Institute',
    logo_url: null,
    registration_number: 'JAM/GOV/2022/CBCI-7789',
    description: 'Caribbean Basin Blue Carbon Institute provides verification services across the Caribbean, with particular expertise in hurricane-resilient mangrove restoration and coral reef carbon assessment. We serve 14 Caribbean nations.',
    mission: 'Strengthening climate resilience in Small Island Developing States through trustworthy blue carbon verification.',
    founded_year: 2022,
    headquarters: 'Kingston, Jamaica',
    operating_regions: ['Jamaica', 'Bahamas', 'Trinidad', 'Belize', 'Honduras'],
    countries_served: ['Jamaica', 'Bahamas', 'Trinidad and Tobago', 'Belize', 'Honduras', 'Cuba', 'Dominican Republic', 'Barbados'],
    states_covered: ['Kingston', 'New Providence', 'San Fernando', 'Stann Creek', 'Atlántida'],
    expertise: ['Mangrove Restoration', 'Coral Reef Carbon', 'Hurricane Resilience', 'Blue Carbon', 'Coastal Adaptation'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Underwater Survey', 'Community Impact Assessment'],
    supported_ecosystems: ['Mangroves', 'Coral Reefs', 'Seagrass Beds', 'Coastal Wetlands'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'Gold Standard' },
    ],
    projects_certified: 28,
    active_applications: 5,
    avg_verification_days: 21,
    years_of_operation: 4,
    available_audit_teams: 2,
    estimated_review_days: 16,
    availability: 'limited',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Belize Barrier Reef Mangrove Shield', status: 'approved', date: '2026-06-22' },
      { project_name: 'Portland Parish Coastal Restoration', status: 'approved', date: '2026-04-30' },
      { project_name: 'San Salvador Mangrove Recovery', status: 'approved', date: '2026-02-15' },
    ],
  },
  {
    id: 'ngo-012',
    profile_id: 'verifier-012',
    profile_id_internal: 'vint-012',
    verifier_ids: ['vr-023'],
    audit_team_ids: ['at-017'],
    regional_office_ids: ['ro-018'],
    name: 'Gulf Blue Carbon Initiative',
    logo_url: null,
    registration_number: 'ARE/GOV/2023/GBCI-2234',
    description: 'Gulf Blue Carbon Initiative is the first dedicated verification body for arid coastal ecosystems in the Arabian Gulf. We specialize in verifying mangrove and sabkha restoration projects in extreme arid conditions.',
    mission: 'Pioneering verification standards for arid-zone blue carbon ecosystems in the Middle East and North Africa.',
    founded_year: 2023,
    headquarters: 'Abu Dhabi, UAE',
    operating_regions: ['Abu Dhabi', 'Dubai', 'Ras Al Khaimah', 'Doha', 'Muscat'],
    countries_served: ['UAE', 'Saudi Arabia', 'Qatar', 'Oman', 'Bahrain'],
    states_covered: ['Abu Dhabi', 'Dubai', 'Al Khor', 'Muscat', 'Muharraq'],
    expertise: ['Arid Coastal Restoration', 'Mangrove Restoration', 'Sabkha Ecosystems', 'Blue Carbon', 'Desalination Impact Assessment'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Satellite Monitoring', 'Environmental Impact Assessment'],
    supported_ecosystems: ['Mangroves', 'Sabkha', 'Seagrass', 'Coral Reefs'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'ISO 14001' },
    ],
    projects_certified: 15,
    active_applications: 3,
    avg_verification_days: 16,
    years_of_operation: 3,
    available_audit_teams: 2,
    estimated_review_days: 12,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Abu Dhabi Mangrove Plantation Phase II', status: 'approved', date: '2026-07-06' },
      { project_name: 'Al Wathba Wetland Reserve Expansion', status: 'approved', date: '2026-05-18' },
      { project_name: 'Sharjah Coast Sabkha Restoration', status: 'approved', date: '2026-03-10' },
    ],
  },
  {
    id: 'ngo-013',
    profile_id: 'verifier-013',
    profile_id_internal: 'vint-013',
    verifier_ids: ['vr-024', 'vr-025'],
    audit_team_ids: ['at-018', 'at-019'],
    regional_office_ids: ['ro-019', 'ro-020'],
    name: 'North America Coastal Trust',
    logo_url: null,
    registration_number: 'USA/GOV/2021/NACT-5567',
    description: 'North America Coastal Trust is a federally recognized verification body covering the United States and Canadian coastlines. We certify salt marsh, mangrove (Florida), and eelgrass restoration projects across 18 coastal states.',
    mission: 'Advancing coastal carbon sequestration through the highest standards of verification and transparent governance.',
    founded_year: 2021,
    headquarters: 'Charleston, South Carolina, USA',
    operating_regions: ['Southeast US', 'Gulf Coast', 'Pacific Northwest', 'Atlantic Canada', 'Maritimes'],
    countries_served: ['United States', 'Canada'],
    states_covered: ['South Carolina', 'Florida', 'Louisiana', 'Oregon', 'British Columbia', 'Nova Scotia'],
    expertise: ['Salt Marsh', 'Mangrove Restoration', 'Eelgrass', 'Blue Carbon', 'Coastal Resilience'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Satellite Monitoring', 'LiDAR Survey', 'Drone Survey'],
    supported_ecosystems: ['Salt Marshes', 'Mangroves', 'Eelgrass', 'Kelp Forests', 'Coastal Wetlands'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'ISO 14001' },
      { name: 'Verra VCS Certified' },
      { name: 'Climate Action Reserve' },
    ],
    projects_certified: 61,
    active_applications: 9,
    avg_verification_days: 17,
    years_of_operation: 5,
    available_audit_teams: 3,
    estimated_review_days: 13,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Charleston Harbor Salt Marsh Revival', status: 'approved', date: '2026-07-09' },
      { project_name: 'Florida Keys Mangrove Restoration', status: 'approved', date: '2026-06-03' },
      { project_name: 'Puget Sound Eelgrass Recovery', status: 'approved', date: '2026-04-22' },
    ],
  },
  {
    id: 'ngo-014',
    profile_id: 'verifier-014',
    profile_id_internal: 'vint-014',
    verifier_ids: ['vr-026', 'vr-027'],
    audit_team_ids: ['at-020'],
    regional_office_ids: ['ro-021'],
    name: 'South Asia Coastal Verification Network',
    logo_url: null,
    registration_number: 'LKA/GOV/2022/SACV-3345',
    description: 'South Asia Coastal Verification Network provides affordable, community-driven verification for small and medium-scale blue carbon projects. We focus on making verification accessible to grassroots organizations and local communities.',
    mission: 'Democratizing blue carbon verification by making it affordable, accessible, and community-centered.',
    founded_year: 2022,
    headquarters: 'Colombo, Sri Lanka',
    operating_regions: ['Western Province', 'Southern Province', 'Northern Province', 'Tamil Nadu', 'Kerala'],
    countries_served: ['Sri Lanka', 'India', 'Maldives', 'Bangladesh', 'Nepal'],
    states_covered: ['Western Province', 'Southern Province', 'Tamil Nadu', 'Kerala', 'Dhaka', 'Chittagong'],
    expertise: ['Community-Led Verification', 'Mangrove Restoration', 'Coastal Wetlands', 'Blue Carbon', 'Small-Scale Projects'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Community Impact Assessment', 'Capacity Building'],
    supported_ecosystems: ['Mangroves', 'Coastal Wetlands', 'Lagoons', 'River Deltas'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
    ],
    projects_certified: 37,
    active_applications: 6,
    avg_verification_days: 24,
    years_of_operation: 4,
    available_audit_teams: 2,
    estimated_review_days: 18,
    availability: 'accepting',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'Negombo Lagoon Community Restoration', status: 'approved', date: '2026-06-18' },
      { project_name: 'Rameswaram Island Mangroves', status: 'approved', date: '2026-05-01' },
      { project_name: 'Sundarbans Community Guardian Project', status: 'approved', date: '2026-03-12' },
    ],
  },
  {
    id: 'ngo-015',
    profile_id: 'verifier-015',
    profile_id_internal: 'vint-015',
    verifier_ids: ['vr-028', 'vr-029', 'vr-030'],
    audit_team_ids: ['at-021', 'at-022'],
    regional_office_ids: ['ro-022', 'ro-023'],
    name: 'Pan-African Wetlands Verification Hub',
    logo_url: null,
    registration_number: 'ZAF/GOV/2020/PAWV-6678',
    description: 'Pan-African Wetlands Verification Hub is the continent\'s largest verification network, spanning 14 countries from Senegal to Mozambique. Our team of 50+ auditors provides comprehensive coverage of Africa\'s diverse wetland ecosystems.',
    mission: 'Building a continent-wide verification infrastructure that supports Africa\'s blue carbon leadership.',
    founded_year: 2020,
    headquarters: 'Cape Town, South Africa',
    operating_regions: ['Western Cape', 'KwaZulu-Natal', 'Mozambique Coast', 'West African Coast', 'East African Coast'],
    countries_served: ['South Africa', 'Mozambique', 'Tanzania', 'Kenya', 'Senegal', 'Nigeria', 'Ghana', 'Madagascar', 'Cameroon', 'Guinea-Bissau', 'Equatorial Guinea', 'Gabon', 'Congo', 'Angola'],
    states_covered: ['Western Cape', 'KwaZulu-Natal', 'Maputo', 'Coast Province', 'Dakar', 'Lagos', 'Accra'],
    expertise: ['Wetlands', 'Mangrove Restoration', 'Forest Restoration', 'Blue Carbon', 'Biodiversity', 'Community Engagement'],
    services: ['Land Verification', 'Field Audit', 'Carbon Certification', 'Biodiversity Assessment', 'Satellite Monitoring', 'Community Impact Assessment'],
    supported_ecosystems: ['Wetlands', 'Mangroves', 'River Deltas', 'Coastal Forests', 'Floodplain Wetlands'],
    certifications: [
      { name: 'Government Registered' },
      { name: 'Blue Carbon Certified' },
      { name: 'Gold Standard' },
      { name: 'Verra VCS Certified' },
      { name: 'ISO 14001' },
    ],
    projects_certified: 104,
    active_applications: 12,
    avg_verification_days: 23,
    years_of_operation: 6,
    available_audit_teams: 5,
    estimated_review_days: 17,
    availability: 'limited',
    verification_status: 'active',
    accepts_new_applications: true,
    paused: false,
    recent_projects: [
      { project_name: 'iSimangaliso Wetland Park Expansion', status: 'approved', date: '2026-07-11' },
      { project_name: 'Senegal Saloum Delta Restoration', status: 'approved', date: '2026-06-08' },
      { project_name: 'Mozambique Zambezi Delta Revival', status: 'approved', date: '2026-04-25' },
    ],
  },
];

export const MOCK_APPLICATIONS: VerificationApplication[] = [];
export const MOCK_AUDIT_REPORTS: AuditReport[] = [];
export const MOCK_OFFICIAL_RECORDS: OfficialRecord[] = [];

export const MOCK_ANALYTICS: VOCAnalytics = {
  total_applications: 0,
  approval_rate: 0,
  avg_verification_time_hours: 0,
  rejected_count: 0,
  returned_count: 0,
  audit_completion_rate: 0,
  by_status: [],
  by_month: [],
};

export const MOCK_CALENDAR_EVENTS: VOCCalendarEvent[] = [];
